title: Climbuddy Blog
author: Team Climbuddy
email: contact@climbuddy.com

description: Updates / articles about Climbuddy.com.
html-description: Updates / articles about <a href="https://climbuddy.com">Climbuddy.com</a>.

baseurl: ""
url: "https://blog.climbuddy.com"
twitter_username: Climbuddy
github_username: Climbuddy
instagram_username: Climbuddy
youtube_username: Climbuddy
rss: RSS

# Build settings
theme: minima
plugins:
  - jekyll-feed

permalink: /:title/

exclude:
  - ignored
